#!/usr/bin/env bash
# 覆盖 auto-resolve-conflicts.sh 的规则化冲突解决，以及 merge-upstream-auto.sh 在
# 冲突无法自动解决 / 已是最新 / 工作区不干净时的行为。需兼容 macOS Bash 3。

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

suite_tmp="$(mktemp -d)"
trap 'rm -rf "$suite_tmp"' EXIT

new_repo() {
  local dir="$1"
  mkdir -p "$dir"
  git -C "$dir" init -q
  git -C "$dir" config user.name "Fork auto-merge test"
  git -C "$dir" config user.email "fork-auto-merge-test@example.invalid"
  git -C "$dir" config core.autocrlf false
  mkdir -p "$dir/.fork" "$dir/.github/workflows"
  cp "$ROOT/.fork/auto-resolve-conflicts.sh" \
    "$ROOT/.fork/merge-upstream-auto.sh" \
    "$ROOT/.fork/merge-upstream-preserving-workflows.sh" \
    "$ROOT/.fork/restore-managed-workflows.sh" \
    "$dir/.fork/"
  printf 'name: fork\n' >"$dir/.github/workflows/ci.yml"
}

write_files() {
  local dir="$1" side="$2"
  mkdir -p "$dir/backend/cmd/server" "$dir/backend/ent/schema"
  printf '%s\n' "$3" >"$dir/backend/cmd/server/VERSION"
  # 双方各自在末尾追加依赖校验和，是 go.sum 最常见的冲突形态
  printf 'a v1 h1:base\nb v1 h1:base\n' >"$dir/backend/go.sum"
  if [[ -n "$4" ]]; then
    printf '%s\n' "$4" >>"$dir/backend/go.sum"
  fi
  printf '// Code generated by ent, DO NOT EDIT.\n\npackage ent\n\n// %s\n' "$side" >"$dir/backend/ent/client.go"
  printf '// Code generated by Wire. DO NOT EDIT.\n\npackage main\n\n// %s\n' "$side" >"$dir/backend/cmd/server/wire_gen.go"
  printf 'package schema\n\n// %s\n' "$side" >"$dir/backend/ent/schema/user.go"
  printf 'package ent\n\n// %s\n' "$side" >"$dir/backend/ent/tx_context.go"
  printf '%s\n' "$side" >"$dir/app.txt"
}

# 构造 fork/upstream 两侧都修改了同一批文件的仓库，HEAD 停在 fork 分支
setup_conflict_repo() {
  local dir="$1"
  new_repo "$dir"
  write_files "$dir" base 1.0.0 ''
  git -C "$dir" add -A
  git -C "$dir" commit -qm "common base"
  git -C "$dir" branch upstream
  write_files "$dir" fork 1.0.0-fork 'c v1 h1:fork'
  git -C "$dir" add -A
  git -C "$dir" commit -qm "fork changes"
  git -C "$dir" checkout -q upstream
  write_files "$dir" upstream 1.1.0 'd v1 h1:upstream'
  git -C "$dir" add -A
  git -C "$dir" commit -qm "upstream changes"
  git -C "$dir" checkout -q -
}

# --- 规则化冲突解决 ---
rules="$suite_tmp/rules"
setup_conflict_repo "$rules"
git -C "$rules" merge -q --no-edit upstream >/dev/null 2>&1 && fail "测试仓库应产生冲突"

set +e
(cd "$rules" && bash .fork/auto-resolve-conflicts.sh >/dev/null 2>&1)
status=$?
set -e
[[ "$status" -eq 2 ]] || fail "仍有手写代码冲突时应返回 2，实际 $status"

remaining="$(git -C "$rules" diff --name-only --diff-filter=U | tr '\n' ' ')"
[[ "$remaining" == "app.txt backend/ent/schema/user.go backend/ent/tx_context.go " ]] \
  || fail "应只剩手写文件冲突（含 ent/schema 与无生成标记的 ent 文件），实际: $remaining"

grep -Fqx '1.1.0' "$rules/backend/cmd/server/VERSION" || fail "VERSION 应采用上游版本"
for line in 'a v1 h1:base' 'b v1 h1:base' 'c v1 h1:fork' 'd v1 h1:upstream'; do
  grep -Fqx "$line" "$rules/backend/go.sum" || fail "go.sum 并集缺少: $line"
done
if grep -Eq '^(<<<<<<<|=======|>>>>>>>)' "$rules/backend/go.sum"; then
  fail "go.sum 不应残留冲突标记"
fi
grep -Fqx '// fork' "$rules/backend/ent/client.go" || fail "ent 生成文件应先以 fork 版本占位"
grep -Fqx '// fork' "$rules/backend/cmd/server/wire_gen.go" || fail "wire_gen.go 应先以 fork 版本占位"
git -C "$rules" merge --abort

# --- 编排脚本：规则无法解决且未配置 AI 时，停止并回滚 ---
orchestrator="$suite_tmp/orchestrator"
setup_conflict_repo "$orchestrator"
start="$(git -C "$orchestrator" rev-parse HEAD)"
summary_file="$suite_tmp/summary.md"
set +e
(
  cd "$orchestrator"
  env -u DEEPSEEK_API_KEY GITHUB_STEP_SUMMARY="$summary_file" \
    bash .fork/merge-upstream-auto.sh "$start" "test: merge upstream" upstream >/dev/null 2>&1
)
status=$?
set -e
[[ "$status" -eq 2 ]] || fail "无法自动解决的冲突应返回 2，实际 $status"
[[ "$(git -C "$orchestrator" rev-parse HEAD)" == "$start" ]] || fail "失败后 HEAD 应回到合并前"
if git -C "$orchestrator" rev-parse -q --verify MERGE_HEAD >/dev/null; then
  fail "失败后不应停留在合并状态"
fi
[[ -z "$(git -C "$orchestrator" status --porcelain)" ]] || fail "失败后工作区应保持干净"
grep -Fq '`app.txt`' "$summary_file" || fail "job summary 应列出需要人工处理的冲突文件"
if grep -Fq 'backend/cmd/server/VERSION' "$summary_file"; then
  fail "job summary 不应列出已按规则解决的文件"
fi

# --- 编排脚本：已是最新时直接成功 ---
set +e
(cd "$orchestrator" && bash .fork/merge-upstream-auto.sh "$start" "test: noop" HEAD~1 >/dev/null 2>&1)
status=$?
set -e
[[ "$status" -eq 0 ]] || fail "已是最新时应返回 0，实际 $status"
[[ "$(git -C "$orchestrator" rev-parse HEAD)" == "$start" ]] || fail "已是最新时不应产生提交"

# --- 编排脚本：工作区不干净时拒绝执行，且不改动任何内容 ---
printf 'local edit\n' >>"$orchestrator/app.txt"
set +e
(cd "$orchestrator" && bash .fork/merge-upstream-auto.sh "$start" "test: dirty" upstream >/dev/null 2>&1)
status=$?
set -e
[[ "$status" -eq 1 ]] || fail "工作区不干净时应返回 1，实际 $status"
grep -Fqx 'local edit' "$orchestrator/app.txt" || fail "拒绝执行时不得丢弃本地修改"

echo "PASS: 规则化冲突解决与自动合并编排行为符合预期"
